<?php

namespace SiteBundle\Repository;

/**
 * FortificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortificationRepository extends \Doctrine\ORM\EntityRepository
{
}
