<?php

namespace SiteBundle\Repository;

/**
 * FortificationOnPlanetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortificationOnPlanetRepository extends \Doctrine\ORM\EntityRepository
{
}
