<?php

namespace SiteBundle\Repository;

/**
 * MessagesBanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesBanRepository extends \Doctrine\ORM\EntityRepository
{
}
