<?php

namespace SiteBundle\Repository;

/**
 * MessagesBansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesBansRepository extends \Doctrine\ORM\EntityRepository
{
}
