<?php

namespace SiteBundle\Repository;

/**
 * PartOfUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartOfUserRepository extends \Doctrine\ORM\EntityRepository
{
}
