<?php

namespace SiteBundle\Repository;

/**
 * QuestOfPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestOfPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
