<?php

namespace SiteBundle\Repository;

/**
 * QuestsOfPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestsOfPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
