<?php

namespace SiteBundle\Repository;

/**
 * RaportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaportRepository extends \Doctrine\ORM\EntityRepository
{
}
