test_battle_engine:
    resource: "@testBattleEngineBundle/Controller/"
    type:     annotation
    prefix:   /

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /
